version: '2.1'

services:
  my_device:
    image: antonytayron/salt-proxy:latest
    container_name: my_device
    volumes:
      - ./proxy_pki:/etc/salt/pki/proxy
    environment:
      - LOG_LEVEL:INFO
      - PROXYID:my_device
