name: Salt-Proxy on Docker CI

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/.github/*'
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: antonytayron/salt-proxy:3007-ubuntu24 #,antonytayron/salt-proxy:latest

    # - name: security-scan
    #   uses: azure/container-scan@v0
    #   with:
    #     image-name: antonytayron/salt-proxy:latest
