name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docer:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Build the Docker image
      # - uses: actions/checkout@v3
      #     run: docker build . --file Dockerfile --tag antonytayron/salt-proxy:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # - name: Build and push
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     platforms: linux/amd64,linux/arm/v7
    #     push: ${{ github.event_name != 'pull_request' }}
    #     tags: ${{ steps.<meta_id>.outputs.tags }}
    #     labels: ${{ steps.<meta_id>.outputs.labels }}
